version: '3'

services:

  php-fpm:
    build:
      context: ./docker/php/
    container_name: movie-recommendations-app
    restart: always
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    #stdin_open: true
    #tty: true
